config/routes.rb
Rails.application.routes.draw do



  root 'welcome#index'

  get '/about', to: 'welcome#about'

  get '/contact', to: 'welcome#contact'

  resources :shipments

  get '/search', to: 'shipments#search'

  get '/track', to: 'shipments#track'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  def self.search(search)
    if search.present?
      where("trackingnumber @@ :q", q: search)
    else
      scoped
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.new(shipment_params)

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].present?
      @shipments = Shipment.search(params[:search])
    else
      @shipments = Shipment.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:trackingnumber, :destination, :status, :lastscan, :originlocation, :sendername, :receivername)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shipment_helper.rb
module ShipmentHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_search_form.html.erb
    <form action="<%= search_path %>" method="get" id="search-form">

    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-8">
        <%= text_field_tag :search, params[:search], placeholder: "Enter Tracking Number", autofocus: true, class: 'form-control search-box input-lg' %>
      </div>
      <div class="col-md-4">
        <%= submit_tag "Track Shipment", class: "form-control search-box input-lg", :name => nil %>
        </form>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FastEx Logistics International</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="/" class="navbar-brand">FastEx Logistics International</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="about">About Us</a></li>
            <li><a href="contact">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
  <footer>
  <p>&copy; 2016. [All Rights Reserved]</p>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">

</script>
</html>

app/views/shipments/_form.html.erb
<%= form_for(shipment) do |f| %>
  <% if shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% shipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sendername, "Sender's Name" %>
    <%= f.text_field :sendername %>
  </div>

  <div class="field">
    <%= f.label :receivername, "Receiver's Name" %>
    <%= f.text_field :receivername %>
  </div>

  <div class="field">
    <%= f.label :originlocation, "Shipped From" %>
    <%= f.text_field :originlocation %>
  </div>

  <div class="field">
    <%= f.label :trackingnumber, 'Tracking Number' %>
    <%= f.text_field :trackingnumber %>
  </div>

  <div class="field">
    <%= f.label :destination, "Destination Country" %>
    <%= f.text_field :destination %>
  </div>

  <div class="field">
    <%= f.label :status, "Shipment Status" %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :lastscan, "Current/Last Known Location" %>
    <%= f.text_field :lastscan %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editing Shipment</h1>

<%= render 'form', shipment: @shipment %>

<%= link_to 'Show', @shipment %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shipments</h1>
<% if @shipments.blank? %>
  <h4>There are no shipment containing the term <%= params[:search] %>.</h4>
<% end %>
<table>
  <thead>
    <tr>
      <th>Sender's Name</th>
      <th>Receiver's Name</th>
      <th>Shipped From</th>
      <th>Tracking Number</th>
      <th>Destination</th>
      <th>Status</th>
      <th>Current / Last Known Location</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= shipment.sendername %></td>
        <td><%= shipment.receivername %></td>
        <td><%= shipment.originlocation %></td>
        <td><%= shipment.trackingnumber %></td>
        <td><%= shipment.destination %></td>
        <td><%= shipment.status %></td>
        <td><%= shipment.lastscan %></td>
        <td><%= link_to 'Show', shipment %></td>
        <td><%= link_to 'Edit', edit_shipment_path(shipment) %></td>
        <td><%= link_to 'Destroy', shipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/new.html.erb
<h1>New Shipment</h1>

<%= render 'form', shipment: @shipment %>

<%= link_to 'Back', shipments_path %>

app/views/shipments/search.html.erb
<h1>Shipments</h1>


    <% @shipments.each do |shipment| %>
    <p>  <strong>Sender's Name: </strong> <%= shipment.sendername %> </p>
    <p>  <strong>Recipient's Name: </strong> <%= shipment.receivername %> </p>
    <p>  <strong>Shipped From: </strong> <%= shipment.originlocation %> </p>
    <p>  <strong>Tracking Number: </strong> <%= shipment.trackingnumber %></p>
    <p>  <strong>Destination: </strong> <%= shipment.destination %></p>
    <p>  <strong>Status: </strong> <%= shipment.status %></p>
    <p>  <strong>Current/Last Known Location:</strong> <%= shipment.lastscan %></p>

    <% end %>

<br>
<%= link_to 'Track Another Package', track_path, class: "btn btn-success" %> |  <%= link_to 'Exit & Return to Home', root_path, class: "btn btn-default" %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender's Name:</strong>
  <%= @shipment.sendername %>
</p>

<p>
  <strong>Receiver's Name:</strong>
  <%= @shipment.receivername %>
</p>

<p>
  <strong>Shipped From:</strong>
  <%= @shipment.originlocation %>
</p>

<p>
  <strong>Tracking Number:</strong>
  <%= @shipment.trackingnumber %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @shipment.destination %>
</p>

<p>
  <strong>Status:</strong>
  <%= @shipment.status %>
</p>

<p>
  <strong>Current / Last Know Location:</strong>
  <%= @shipment.lastscan %>
</p>

<%= link_to 'Edit', edit_shipment_path(@shipment) %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/track.html.erb
<div id="search-bar">
  <%= render 'common/search_form' %>
</div>

app/views/welcome/about.html.erb
<div class="container">
  <div class="container">
    <h1>About Us</h1>
    <p>With a comprehensive range of services covering all modes of transportation, we are totally committed to providing quality, flexibility & reliability. Our policy is to listen to you, the customer, and develop our services around your own specific needs, rather than expecting you to adapt to our operating procedures.</p>
    <p>All of our personnel are fully versed in the technicalities of import and export procedures, and are dedicated to taking away from you the headaches of international distribution, whether this is for on-going contracts, a specific project or one off movements. It is our job to ensure you are continuously given clear, concise and up to date information at all times, whilst ensuring the movement of your goods is expedited in the most professional manner.</p>
    <p>We are committed to a policy of continual development and improvement, both with the systems we operate and the levels of service we provide to our clientele.</p>
    <p>We believe that we can offer a unique blend of professionalism and flexibility unsurpassed by our competitors within our industry. </p>
    <p> <strong>We offer the following services :</strong></p>
    <ul>
      <li>Intracity Courier Services</li>
      <li>Domestic & </li>
      <li>International Couriers</li>
    </ul>
    <p>We Undertake Pickup & Bulk Delivery of Documents, Booklets, Samples and Parcels such as Printing Materials, Seminar Goods, Machinery parts etc., for More than 2000 cities throughout the world.</p>
    <p>We are also known for the Companies we keep on our customer base and we are certain that, they will stand by us in testimony of the excellent rapport between us.</p>
  </div>
</div>

app/views/welcome/contact.html.erb
<div class="container">
  <form method="post" action="contact/send">
    <h1>Contact Us</h1>
    <div class="form-group">
      <label>Name</label>
      <input type="text" name="name" placeholder="Enter Name" required="required" class="form-control"/>
    </div>
    <div class="form-group">
      <label>Email</label>
      <input id="exampleInputEmail1" type="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" required="required" class="form-control"/><small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label>Message</label>
      <textarea id="exampleTextarea" name="message" placeholder="Enter Message" rows="3" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="jumbotron">
  <div class="container">
    <h1>How May I help You?</h1>
    <p>Have a unique shipping need? Require logistics services support? FastEx Logistics International provides delivery specialists that offer a variety of support services for all types of specialized delivery and logistical needs. </p><a href="contact" class="btn btn-primary btn-lg">Contact Us Today &raquo;</a>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>About Us</h2>
      <p>We bring transportation intelligence to business using our system of drivers and partners to provide customized courier solutions, giving you meaningful and measurable advantages.</p><a href="about" class="btn btn-default">View Details</a>
    </div>
    <div class="col-md-4">
      <h2>Track Package</h2>
      <p>With FLI, you are always guaranteed an efficient and cost effective solution to moving your goods around the country or around the world. No job is ever too near, too far, too big or too small.</p><a href="track" class="btn btn-default">Track Shipment</a>
    </div>
    <div class="col-md-4">
      <h2>Contact Us</h2>
      <p>We work with small, local companies to Fortune 500 corporations with a national footprint. Our greatest asset is our extensive menu of courier services that allow us to customize our solutions to meet each client’s need.</p><a href="contact" class="btn btn-default">View Details</a>
    </div>
  </div>
</div>
  </body>
</html>